version: '3'
services:
  worker:
    container_name: nodejs-vscode-debug.worker
    build: .
    image: nodejs-vscode-debug
    command: /bin/sh -c - "while :; do sleep 1000; done"
    environment:
      TZ: 'Asia/Tokyo'
      PORT: '3000'
    ports:
      - "9229:9229"
      - "3000:3000"
    volumes:
      - ./dist:/app/dist:ro
