version: '3'
services:
  worker:
    container_name: nodejs-vscode-debug.worker
    build: .
    image: nodejs-vscode-debug
    command: npm run start-debug
    environment:
      TZ: 'Asia/Tokyo'
      PORT: '3000'
    ports:
      - "9229:9229"
      - "3000:3000"
